In [1]:
import numpy as np

# Ratings matrix
R = np.array([
    [5, 3, 0],
    [4, 0, 0],
    [1, 1, 0]
], dtype=float)

# Hyperparameters
K = 2
alpha = 0.01
steps = 1000
lambda_reg = 0.1

# Dimensions
num_users, num_items = R.shape

# Latent matrices (your chosen values)
U = np.array([
    [0.8, 0.2],
    [0.5, 0.7],
    [0.9, 0.1]
], dtype=float)

V = np.array([
    [1.0, 0.3],
    [0.4, 0.8],
    [0.2, 0.9]
], dtype=float)

# Gradient Descent Training Loop
for step in range(steps):
    for i in range(num_users):
        for j in range(num_items):
            if R[i, j] > 0:
                # Prediction
                R_hat_ij = np.dot(U[i, :], V[j, :])

                # Error
                e_ij = R_hat_ij - R[i, j]

                # Update rules (simple version)
                U[i, :] = U[i, :] - alpha * (e_ij * V[j, :]) - lambda_reg * U[i, :]
                V[j, :] = V[j, :] - alpha * (e_ij * U[i, :]) - lambda_reg * V[j, :]

# Final predicted matrix
final_result = np.dot(U, V.T)

print("Predicted R matrix:")
print(final_result)

Predicted R matrix:
[[1.92567373e-86 2.61813310e-87 7.59565456e-44]
 [1.84496052e-85 2.50839595e-86 7.27728822e-43]
 [4.09106180e-87 5.56218019e-88 1.61368417e-44]]
