In [ ]:
import numpy as np

points = np.array([
    [1,2,3],
    [1,1,1],
    [3,2,1]
])

print("shape:", points.shape)

print("row 0:", points[0])
print("column 0:", points[:,0])
print(points[:,1])
print("mean axis 0:", np.mean(points, axis=0))
print("mean axis 1:", np.mean(points, axis=1))

shape: (3, 3)
row 0: [1 2 3]
column 0: [1 1 3]
[2 1 2]
mean axis 0: [1.66666667 1.66666667 1.66666667]
mean axis 1: [2. 1. 2.]


In [ ]:
import numpy as np

points = np.array([
    [1,2,3],
    [1,1,1],
    [1,1,1],
    [3,2,3],
    [3,2,1]
])

centroids = np.array([
    [1,2,3],
    [1,1,1],
    [3,2,1]
])

print(points[:, np.newaxis, :])
diff = points[:, np.newaxis, :] - centroids
print("diff shape:", diff.shape)

dist = np.sqrt(np.sum(diff**2, axis=2))
print("distance matrix:\n", dist)

assignments = np.argmin(dist, axis=1)
print("assignments:", assignments)

[[[1 2 3]]

 [[1 1 1]]

 [[1 1 1]]

 [[3 2 3]]

 [[3 2 1]]]
diff shape: (5, 3, 3)
distance matrix:
 [[0.         2.23606798 2.82842712]
 [2.23606798 0.         2.23606798]
 [2.23606798 0.         2.23606798]
 [2.         3.         2.        ]
 [2.82842712 2.23606798 0.        ]]
assignments: [0 1 1 0 2]


Exercise 1 — Axis mastery
points = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

👉 Find:

1️⃣ sum of each column
2️⃣ sum of each row

In [ ]:
points = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("sum of rows", np.sum(points, axis = 1))
print("sum of columns", np.sum(points, axis = 0))

sum of rows [ 6 15 24]
sum of columns [12 15 18]


In [ ]:
points = np.array([
    [1,2,3],
    [4,5,6]
])

centroid = np.array([1,1,1])
#Compute:(points - centroid)^2
print(np.shape(points))
np.shape((centroid))
print((points - centroid) ^ 2)

(2, 3)
[[2 3 0]
 [1 6 7]]


In [ ]:
dist = np.array([
    [2,5,3],
    [1,6,7],
    [4,3,1]
])
np.argmin(dist, axis=0)

array([1, 2, 2])

In [ ]:
a = np.array([1,2,3])
b = np.array([[1,2],[2,2],[3,2]])
c = np.array([[1],[2],[3]])
d = np.array([
  [
    [0, 1],
    [16, 9]
  ],
  [
    [4, 9],
    [4, 1]
  ]
])
print(np.shape(a))
print(np.shape(b))
print(np.shape(c))
print(np.shape(d))

(3,)
(3, 2)
(3, 1)
(2, 2, 2)


##Distance from a single centroid

In [ ]:
points = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

centroid = np.array([1, 1])
result = points - centroid
print(result)