In [6]:
import numpy as np

R = np.array(
    [
    [5, 3, 0],
    [4, 0, 0],
    [1, 1, 0]
    ],dtype=float)

k = 2
alpha = 0.05
steps=1000
lamda_reg = 0.01
num_user, num_items = R.shape
U = np.array([
    [0.8, 0.2],
    [0.5, 0.7],
    [0.9, 0.1]
], dtype=float)
V = np.array([
    [1.0, 0.3],
    [0.4, 0.8],
    [0.2, 0.9]
], dtype=float)


for step in range(steps):
  for i in range(num_user):
    for j in range(num_items):
      if R[i,j] > 0:
       R_hat_ij = np.dot(U[i, :],V[j, :])
       e_ij = R_hat_ij - R[i,j]
       U_old = U[i, :].copy()
       U[i, :] = U[i, :] - alpha * (e_ij * V[j, :]) - lamda_reg * U[i, :]
       V[j, :] = V[j, :] - alpha * (e_ij * U_old) - lamda_reg * V[j, :]

fina_result = np.dot(U,V.T)
print(fina_result)



[[4.61215737 2.84948323 1.44121461]
 [3.76384517 2.32537887 1.17601053]
 [1.09038532 0.67366214 0.34104074]]
