In [82]:
import numpy as np

items = np.array([
    [1.0, 1.2, 5.0, 5.2],
    [0.8, 1.0, 4.8, 5.0],
    [9.0, 9.2, 0.5, 0.6],
    [8.8, 9.0, 0.4, 0.7],
    [1.2, 0.9, 4.9, 5.1]
])

k = 2
np.random.seed(42)
rand_vectors = np.random.choice(len(items), k, replace=False)
initial_centroids = items[rand_vectors]
print("initial_centroids:\n", initial_centroids)

old_clusters = None

while True:

    # K2: distance matrix
    dist = np.zeros((len(items), k))
    for i in range(len(items)):
        for j in range(k):
            dist[i,j] = np.sum((items[i] - initial_centroids[j]) ** 2)

    print("\ndist matrix:\n", dist)

    # K3: assignments
    initial_clusters = np.argmin(dist, axis=1)
    print("\ncluster assignments:", initial_clusters)

    # K7: stopping condition
    if old_clusters is not None and np.array_equal(initial_clusters, old_clusters):
        print("\nClusters stabilized. STOP.")
        break

    old_clusters = initial_clusters.copy()

    # K4: compute new centroids
    new_centroids = np.zeros((k, items.shape[1]))

    for ci in range(k):
        cluster_items = []

        for ri in range(len(items)):
            if initial_clusters[ri] == ci:
                cluster_items.append(items[ri])

        cluster_items = np.array(cluster_items)
        print(f"\nCluster {ci} items:\n", cluster_items)

        new_centroids[ci] = np.mean(cluster_items, axis=0)

    print("\nnew centroids:\n", new_centroids)

    # K5: update centroids
    initial_centroids = new_centroids.copy()



initial_centroids:
 [[0.8 1.  4.8 5. ]
 [1.2 0.9 4.9 5.1]]

dist matrix:
 [[1.6000e-01 1.5000e-01]
 [0.0000e+00 1.9000e-01]
 [1.7233e+02 1.6934e+02]
 [1.6585e+02 1.6298e+02]
 [1.9000e-01 0.0000e+00]]

cluster assignments: [1 0 1 1 1]

Cluster 0 items:
 [[0.8 1.  4.8 5. ]]

Cluster 1 items:
 [[1.  1.2 5.  5.2]
 [9.  9.2 0.5 0.6]
 [8.8 9.  0.4 0.7]
 [1.2 0.9 4.9 5.1]]

new centroids:
 [[0.8   1.    4.8   5.   ]
 [5.    5.075 2.7   2.9  ]]

dist matrix:
 [[1.6000000e-01 4.1595625e+01]
 [0.0000000e+00 4.3065625e+01]
 [1.7233000e+02 4.3145625e+01]
 [1.6585000e+02 3.9975625e+01]
 [1.9000000e-01 4.1550625e+01]]

cluster assignments: [0 0 1 1 0]

Cluster 0 items:
 [[1.  1.2 5.  5.2]
 [0.8 1.  4.8 5. ]
 [1.2 0.9 4.9 5.1]]

Cluster 1 items:
 [[9.  9.2 0.5 0.6]
 [8.8 9.  0.4 0.7]]

new centroids:
 [[1.         1.03333333 4.9        5.1       ]
 [8.9        9.1        0.45       0.65      ]]

dist matrix:
 [[4.77777778e-02 1.66225000e+02]
 [6.11111111e-02 1.69065000e+02]
 [1.70304444e+02 2.5000000