In [11]:
import numpy as np

# Small example rating matrix (0 = missing)
R = np.array([
    [5, 0, 0, 2],
    [0, 4, 3, 0],
    [1, 0, 0, 0]
])

num_users, num_items = R.shape
K = 2  # latent dim

# Initialize U and V randomly
U = np.random.rand(num_users, K)
V = np.random.rand(num_items, K)

alpha = 0.01  # learning rate
lambda_reg = 0.1
epochs = 1

for ep in range(epochs):
    for u in range(num_users):
        for i in range(num_items):

            if R[u, i] > 0:  # only observed ratings
                pred = U[u, :].dot(V[i, :])
                error = R[u, i] - pred

                # Update U and V
                U[u, :] += alpha * (error * V[i, :] - lambda_reg * U[u, :])
                V[i, :] += alpha * (error * U[u, :] - lambda_reg * V[i, :])

predicted_R = U.dot(V.T)
print(predicted_R)

[[0.54106318 0.4247973  0.49741543 0.26405343]
 [0.5250953  0.38310018 0.46631535 0.28491431]
 [0.96722584 0.65641958 0.83121967 0.57320742]]
